name: opt_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - matplotlib
  - xlsxwriter
  - ipykernel
  - pip
  - pip:
      - git+https://github.com/jcsyme/sisepuede.git@ff05cc079595e3a79c02eeb06ad373117ebbaabc
      - ssp-transformations-handler
      - pyswarm==0.6