target_region: croatia
iso_alpha_3: HRV
stressed_variables_report_version: stressed_variables_report_2025_04_15.xlsx
input_data_file_to_calibrate: croatia_input_data.csv
input_rows: 10
normalization_flag: false
detailed_diff_report_flag: true
energy_model_flag: false
subsector_to_calibrate:
error_type: wmse
weight_type: norm_weight
ssp_edgar_cw: sisepuede_edgar_active_crosswalk.csv
swarmsize: 3
maxiter: 5
