target_region: croatia
iso_alpha_3: HRV
stressed_variables_report_version: stressed_variables_report_2025_02_07.xlsx
input_rows: 10
normalization_flag: false
detailed_diff_report_flag: true
energy_model_flag: false
subsector_to_calibrate:
error_type: wmse
weight_type: norm_weight
swarmsize: 3 
maxiter: 2
