target_region: uganda
iso_alpha_3: UGA
stressed_variables_report_version: stressed_variables_report_2025_06_06.xlsx
input_data_file_to_calibrate: new_uganda_inputs.csv
emission_targets_file: emission_targets_uganda.csv
input_rows: 10
detailed_diff_report_flag: true
energy_model_flag: false
sim_init_year: 2015 # NOTE:Most of the ssp data starts from 2015 but make sure to check the input data file
comparison_init_year: 2020 # Note: this is the initial year to filter the input data file. You need at least 3 years of data for the model to run
comparison_year: 2022 # Note: this is the end year to filter the input data file and also the year to compare the input data file with the targets
subsector_to_calibrate:
error_type: mse
weight_type: norm_weight
ssp_edgar_cw: sisepuede_edgar_active_crosswalk.csv
swarmsize: 468
maxiter: 2
